apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - image: busybox
          name: {{ .Release.Name }}-frontend
          command:
          - sh
          - -c
          - |
            mkdir -p www/cgi-bin &&
            touch www/cgi-bin/hello
            chmod +x www/cgi-bin/hello &&
            tee www/cgi-bin/hello <<-EOSCRIPT && httpd -f -h www
            #!/bin/sh
            echo "Content-Type: text/html"
            echo ""
            echo "This is frontend.<br>"
            echo "<img src=https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Cat_November_2010-1a.jpg/359px-Cat_November_2010-1a.jpg>"
            echo "This is the a web page fetched from the backend server:<pre>"
            echo \$(wget -qO - {{ .Release.Name }}-backend)
            EOSCRIPT
          ports:
            - containerPort: 80
