apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - image: busybox
          name: {{ .Release.Name }}-backend
          command: [sh, -c, "echo 'This is backend' > index.html && httpd -f"]
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-backend